### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Mineru98** [hyunwoongko/pecab#48]
https://github.com/hyunwoongko/pecab/blob/05a8e80b28479f51f7bd430d81a1cffcf5a4c241/mecab/utils/freelist.py#L31

`self.free_list` 크기가 0이면 IndexError가 발생합니다.
그래서 len(self.free_list)으로 길이 체크 후에 0이 아니면, 기존 코드대로 진행하지만 만약 크기가 0이면 다음과 같이 해결하는건 어떨까 싶습니다.
```python
if len(self.free_list) == 0:
    obj = self.free_list = [self.pi_]
    self.pi_ += 1
    return obj
else:
    obj = self.free_list[self.li_] = self.free_list[self.li_] + self.pi_
    self.pi_ += 1
    return obj
```

**Comment by hyunwoongko** [comment]
넵 좋습니다. 수정해서 PR 해놓을게용
