### ISSUE TITLE
pecab에서 단어사전 추가 및 우선순위 조정

### ISSUE THREAD

**Issue by inrap8206** [hyunwoongko/pecab#6]
안녕하세요 현웅님, pecab 잘 쓰고 있습니다!
혹시 pecab에서 단어사전 추가 및 우선순위 조정이 가능한가요?
가능하다면 어느 부분을 수정하면 될까요?

**Comment by hyunwoongko** [comment]
https://github.com/hyunwoongko/pecab#5-pecabuser_dictliststr-applies-an-user-dictionary

단어사전 추가는 이렇게 할 수 있습니다.
혹시 우선순위는 어떤식으로 동작하는 걸 말씀하신 걸까요?

**Comment by inrap8206** [comment]
user_dict을 사용할 수 있군요. 감사합니다!

우선순위는 토크나이징 할때 우선적으로 적용되는 순서를 말한거였습니다.
(공유해주신 페이지를 설명을 보니 토크나이징시 사용자가 등록한 단어를 최우선적으로 적용하는 것 같네요.)

- 토크나이징 대상 문장 : 나는 '대통령표창'을 받았다.
- case1) 토크나이징 우선순위 순서 ①대통령, ②표창, ③대통령표창, 
              토크나이징 결과 => 나, 대통령, 표창 
- case2) 토크나이징 우선순위 ①대통령표창, ②대통령, ③표창
             토크나이징 결과 => 나, 대통령표창

관련 내용이 설명된 페이지 첨부 드립니다.
https://joyhong.tistory.com/136

**Comment by hyunwoongko** [comment]
설명 감사합니다. 
현재는 사용자 단어를 최우선으로 토크나이징 하도록 개발되어있습니다.
대부분 사용자 단어를 사용하시는 분들의 니즈를 반영하기 위함입니다.
